name: 'Branch Protection'

on:
  push:
    branches: [ main, develop ]

jobs:
  protect-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Protect main branch
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/branches/main/protection" \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": ["validate", "build"]
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "required_approving_review_count": 2,
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": true
              },
              "restrictions": null,
              "required_conversation_resolution": true
            }'
            
      - name: Protect develop branch
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/branches/develop/protection" \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": ["validate", "build"]
              },
              "enforce_admins": false,
              "required_pull_request_reviews": {
                "required_approving_review_count": 1,
                "dismiss_stale_reviews": true
              },
              "restrictions": null,
              "required_conversation_resolution": true
            }' 